# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7e9b4374c9d6965ed14144e2023332d8dcc9018e0b82ac282398dd796d3caa6e5d062b2e99fec0f1e7379e265c08e233263340893b8774a94cd9d4506ccb069

test:
  secret_key_base: a9feebb8826009a9ddc3724990ffb1908227435cfd5c09d34d38ffbe801f1eab1cc4fdc898be1c31bdeb1f79bd12ec11d233b243354c01624c35903fc53c9593

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
